CREATE TABLE users (id SERIAL PRIMARY KEY, username VARCHAR(50) UNIQUE, email VARCHAR(100), password_hash TEXT, plan VARCHAR(20) DEFAULT 'trial');
CREATE TABLE attack_logs (id SERIAL PRIMARY KEY, user_id INTEGER, type VARCHAR(50), ip VARCHAR(45), severity VARCHAR(20), timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
